import React from 'react';
import Head from 'next/head';
import { Container, TitlePage, TitleCreatores, Main } from '../../styles/pages/events/style';
import MockProfile from '@/components/MockProfile';

export default function EasterEgg() {

    return (
        <>
            <Head>
                <title>Humanitas | Eventos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <Container>
                    <TitlePage>
                        <TitleCreatores>
                            Criadores do projeto
                        </TitleCreatores>
                        </TitlePage>
                        <MockProfile />
                </Container>
            </Main>
        </>
    );
}